version: '3.8'

services:
  im-chat-app-postgres:
    container_name: im-chat-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: im_chat_app
    networks:
      - im-chat-network

  im-chat-app-server:
    container_name: im-chat-server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    depends_on:
      - im-chat-app-postgres
    environment:
      DATABASE_URL: postgres://postgres:password@im-chat-app-postgres:5432/im_chat_app
    networks:
      - im-chat-network

networks:
  im-chat-network:
